#include "errors.h"
#include "analyseur_lexical.h"
// Error messages
char* errors[ERRORS_NUMBER] = {
	":= symbol was expected",
	"ASSIGNEMENT OR PROCEDURE was expected",
	"A character was expected",
	") symbol was expected",
	"error on CONDITION ",//5
	": symbol was expected ",
	//"DPUN_ERROR",
	"EXPRESSION error",
	//"FACTOR ERROR",
	//"error sequence of statements handled",
	"identifier was expected",
	"symbol not found error",
	"IF symbol was expected",//10
	") symbol was expected",
	"( symbol was expected",
	"SEQUENCE STATEMENT ERROR",
	" ' or \"  symbol was expected",
	"Unrecognized character",//15
	": symbol was expected",
	"symbol exist error",//semantique
	"symbol not found error",
	"unchangeable value of constant",
	"Integer was expected",
	"IN symbol was expected",
	" WHILE symbol was expected",
	" { symbol was expected ",
	" } symbol was expected ",
	" for symbol was expected",
    " identifier or number were expected"
    " repeat symbol was expected",
    "Conddition expected",
    "Sequence of statements expected",
    "Condition expected",
    "SIMPLE Expression expected",
    "Character expected",
    "Character expected",
    "Character expected",
    "Character expected",
    "vector was expected",
    "A function was expected",
    "a String was expected",
    "a boolean was expected",
	"argument non valid",
};


/*
 * Function called to raise an errors generated by
 * the compiler
 */

void raise_error(error_code ec) {
	if (ec >= ERRORS_NUMBER)

		printf("Error number %i: error without a message yet on line %i \n", ec, current_line);
	else{
		
		printf("Error number %i: %s on line %i \n", ec, errors[ec], current_line);

	}	
}
